# ------------------------------------------------------------------------------
# Items endpoints
# 
# ------------------------------------------------------------------------------

# @name Get item by ID
GET http://localhost:5800/items/4
Content-Type: application/json

<> 2023-12-01T173437.200.json
<> 2023-12-01T172733.200.json
###

# ------------------------------------------------------------------------------
# @name Save new item
POST http://localhost:5800/items
Content-Type: application/json

{
  "code": "CODE.031",
  "description": "Testing item - Δοκιμαστικό Είδος",
  "price": 234.2500,
  "alternativeCodes": [
    {
      "code": "ALTER.001",
      "kind": 1,
      "description": "Δοκιμαστικός κωδικός"
    }
  ]
}

<> 2023-12-01T172742.201.json

###

# ------------------------------------------------------------------------------
# @name Save existing item
PUT http://localhost:5800/items/3
Content-Type: application/json

{
  "rowVersion": 1,
  "code": "ITEM.001",
  "description": "Testing item - Modified description",
  "price": 234.2500,
  "alternativeCodes": [
    {
      "code": "ALTER.001",
      "kind": 1,
      "description": "Δοκιμαστικός κωδικός"
    }
  ]
}

<> 2023-12-01T174156.200.json
<> 2023-12-01T174131.409.json


###

# ------------------------------------------------------------------------------
# @name Delete item
DELETE http://localhost:5800/items/2?version=1
Content-Type: application/json

###