# ------------------------------------------------------------------------------
# Items endpoints
# 
# ------------------------------------------------------------------------------

# ------------------------------------------------------------------------------
# @name Save new item
POST http://localhost:5800/items
Content-Type: application/json

{
  "code": "CODE.231",
  "description": "Testing item - Δοκιμαστικό Είδος",
  "price": 234.25,
  "alternativeCodes": [
    {
      "code": "ALTER.401",
      "kind": 1,
      "description": "Δοκιμαστικός κωδικός"
    }
  ]
}

> {% client.global.set("id", response.body.id); %}

###

# ------------------------------------------------------------------------------
# @name Get item by ID
GET http://localhost:5800/items/{{id}}
Content-Type: application/json

> {% client.global.set("version", response.body.rowVersion); %}
###

# ------------------------------------------------------------------------------
# @name Save existing item
PUT http://localhost:5800/items/{{id}}
Content-Type: application/json

{
  "rowVersion": {{version}},
  "code": "ITEM.001",
  "description": "Testing item - Modified description",
  "price": 234.2500,
  "alternativeCodes": [
    {
      "code": "ALTER.001",
      "kind": 1,
      "description": "Δοκιμαστικός κωδικός"
    }
  ]
}

> {% client.global.set("version", response.body.rowVersion); %}

###

# ------------------------------------------------------------------------------
# @name Delete item
DELETE http://localhost:5800/items/{{id}}?version={{version}}
Content-Type: application/json

###
